### ISSUE TITLE
Hyak?

### ISSUE THREAD

**Issue by sr320** [RobertsLab/code#1]
So my first guess is to go here for hyak stuff...? 
Maybe not?

**Comment by sr320** [comment]
I guess I am still learning - hyak has its own repo :)

**Comment by kubu4** [comment]
Yes, and it's linked in this repo's readme file.

**Comment by kubu4** [comment]
The "Super Computing with Mix" link. I'll edit link description to mention Hyak.

**Comment by sr320** [comment]
What type of person comments after an issue is closed?
jk but I am going straight to wiki..  
more evidence for single url ... now I am leaning towards that being onbording readme.
